/***************************************************************************/ /**
 * @file
 * @brief Top level application functions
 *******************************************************************************
 * # License
 * <b>Copyright 2022 Silicon Laboratories Inc. www.silabs.com</b>
 *******************************************************************************
 *
 * The licensor of this software is Silicon Laboratories Inc. Your use of this
 * software is governed by the terms of Silicon Labs Master Software License
 * Agreement (MSLA) available at
 * www.silabs.com/about-us/legal/master-software-license-agreement. This
 * software is distributed to you in Source Code format and is governed by the
 * sections of the MSLA applicable to Source Code.
 *
 ******************************************************************************/
#ifndef AUDIO_CLASSIFIER_H
#define AUDIO_CLASSIFIER_H

#include "sl_sleeptimer.h"
#ifdef __cplusplus
extern "C" {
#endif
#include "led_helper.hpp"

#ifdef __cplusplus
}
#endif

#include "audio_classifier_config.h"
#include "mic_helper.hpp"
#include "sl_ml_audio_feature_generation_config_si91x.h"
#include "sl_ml_audio_feature_generation_si91x.h"

// This header is generated by the NPU Compiler at build-time

#ifdef __cplusplus
extern "C" {
#endif

sl_status_t run_inference();
sl_status_t load_model();
sl_status_t process_output(const bool did_run_inference);
void handle_results(int32_t current_time, int result, uint8_t score, bool is_new_command);
const char* get_category_label(int index);
void voice_control_light_task();

#ifdef __cplusplus
}
#endif

#endif  // AUDIO_CLASSIFIER_H
